name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
      - uses: php-actions/phpstan@v2
        with:
          php_version: 7.4
          path: src
          level: 5

